"""HTML report generation for ActinoEdit."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from actinoedit.core.models import (
    GuideCandidate,
    GuideScore,
    OffTargetHit,
    TargetRegion,
)

# Default HTML template
DEFAULT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ActinoEdit Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1, h2, h3 { color: #333; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #4CAF50; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .warning { background-color: #fff3cd; border: 1px solid #ffc107; padding: 10px; margin: 10px 0; }
        .excellent { color: #28a745; }
        .good { color: #17a2b8; }
        .caution { color: #ffc107; }
        .avoid { color: #dc3545; }
    </style>
</head>
<body>
    <h1>ActinoEdit CRISPR Design Report</h1>

    <h2>Target Information</h2>
    <table>
        <tr><th>Property</th><th>Value</th></tr>
        {% if target %}
        <tr><td>Target</td><td>{{ target.display_label }}</td></tr>
        <tr><td>Contig</td><td>{{ target.contig }}</td></tr>
        <tr><td>Region</td><td>{{ target.start }}-{{ target.end }}</td></tr>
        <tr><td>Strand</td><td>{{ target.strand }}</td></tr>
        {% endif %}
    </table>

    <h2>Design Parameters</h2>
    <table>
        <tr><th>Parameter</th><th>Value</th></tr>
        {% for key, value in parameters.items() %}
        <tr><td>{{ key }}</td><td>{{ value }}</td></tr>
        {% endfor %}
    </table>

    {% if warnings %}
    <h2>Warnings</h2>
    <div class="warning">
        <ul>
        {% for warning in warnings %}
            <li>{{ warning }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}

    <h2>Guide Candidates (Top {{ top_n }})</h2>
    <table>
        <tr>
            <th>Guide ID</th>
            <th>Position</th>
            <th>Strand</th>
            <th>PAM</th>
            <th>GC%</th>
            <th>BGC</th>
            <th>CRISPRi Region</th>
            <th>Dist to Start</th>
            <th>Strand Rel.</th>
            <th>Score</th>
            <th>Recommendation</th>
        </tr>
        {% for guide in guides[:top_n] %}
        <tr>
            <td>{{ guide.guide_id }}</td>
            <td>{{ guide.contig }}:{{ guide.start }}-{{ guide.end }}</td>
            <td>{{ guide.strand }}</td>
            <td>{{ guide.pam }}</td>
            <td>{{ "%.1f"|format(guide.gc_content * 100) }}%</td>
            <td>{{ guide.bgc_context or "" }}</td>
            <td>{{ guide.crispri_region_type or "" }}</td>
            <td>{{ guide.distance_to_start_codon or "" }}</td>
            <td>{{ guide.target_strand_relation or "" }}</td>
            <td>{{ "%.3f"|format(guide_scores[guide.guide_id].final_score) if guide.guide_id in guide_scores else "N/A" }}</td>
            <td class="{{ guide_scores[guide.guide_id].recommendation if guide.guide_id in guide_scores else "" }}">
                {{ guide_scores[guide.guide_id].recommendation_label if guide.guide_id in guide_scores else "N/A" }}
            </td>
        </tr>
        {% endfor %}
    </table>

    <h2>Off-Target Summary</h2>
    <table>
        <tr>
            <th>Guide ID</th>
            <th>0 mismatches</th>
            <th>1 mismatch</th>
            <th>2 mismatches</th>
            <th>3 mismatches</th>
        </tr>
        {% for guide_id, hits in off_target_hits.items() %}
        <tr>
            <td>{{ guide_id }}</td>
            <td>{{ hits | selectattr("mismatch_count", "equalto", 0) | list | length }}</td>
            <td>{{ hits | selectattr("mismatch_count", "equalto", 1) | list | length }}</td>
            <td>{{ hits | selectattr("mismatch_count", "equalto", 2) | list | length }}</td>
            <td>{{ hits | selectattr("mismatch_count", "equalto", 3) | list | length }}</td>
        </tr>
        {% endfor %}
    </table>

    <footer>
        <p><em>Generated by ActinoEdit</em></p>
    </footer>
</body>
</html>
"""


def write_html_report(
    guides: list[GuideCandidate],
    output_path: str | Path,
    target: TargetRegion | None = None,
    scores: list[GuideScore] | None = None,
    off_target_hits: dict[str, list[OffTargetHit]] | None = None,
    parameters: dict[str, str] | None = None,
    warnings: list[str] | None = None,
    top_n: int = 20,
) -> None:
    """Write an HTML report.

    Args:
        guides: List of GuideCandidate objects.
        output_path: Path to output HTML file.
        target: Optional TargetRegion object.
        scores: Optional list of GuideScore objects.
        off_target_hits: Optional dictionary of off-target hits.
        parameters: Optional dictionary of design parameters.
        warnings: Optional list of warning messages.
        top_n: Number of top guides to show.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Create score lookup
    guide_scores = {}
    if scores:
        guide_scores = {s.guide_id: s for s in scores}

    # Prepare template data
    template = Template(DEFAULT_TEMPLATE)
    html = template.render(
        target=target,
        guides=guides,
        guide_scores=guide_scores,
        off_target_hits=off_target_hits or {},
        parameters=parameters or {},
        warnings=warnings or [],
        top_n=top_n,
    )

    with open(output_path, "w") as f:
        f.write(html)
